# Generated by Django 3.2.9 on 2021-11-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=120)),
                ('content_text', models.CharField(max_length=1000)),
                ('today_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
