# Generated by Django 3.2.9 on 2021-12-14 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title_text',
            new_name='post_title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_text',
        ),
        migrations.AddField(
            model_name='post',
            name='post_content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(null=True, upload_to='posts/'),
        ),
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='today_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
