# Generated by Django 3.2.9 on 2022-01-12 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20220108_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created', '-updated']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='today_date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
